#!/usr/bin/env bash
# Copyright 2026 The OpenTacit Authors
# SPDX-License-Identifier: Apache-2.0

# Take the landing page's chrome out of the tacit working copy next door.
#
#   ./hack/sync-site.sh [path-to-tacit-checkout]     # write
#   ./hack/sync-site.sh --check [path]               # compare, exit 1 on drift
#
# This replaced a copy of the palette and a hand-written lookalike masthead. The
# lookalike was the problem: it resolved every colour from the real tokens and
# still did not match, because matching a header means matching its paddings,
# its rule, its wordmark lockup, its icon sizes and the order of its parts — and
# each of those is a value somebody would have had to keep in step by eye.
#
# So nothing here is written by hand. `make site` in the tacit repository renders
# the page and its assets, and this script takes five things out of that bundle:
#
#   assets/css/app.css                  the product's stylesheet, whole
#   static/assets/fonts/                the faces it names, at the paths it names
#   layouts/partials/site-head.html     the head's prelude: favicon, theme init,
#                                       the boot guard and the critical CSS floor
#   layouts/partials/site-masthead.html the masthead, byte for byte but for one
#                                       rewrite: the wordmark becomes a link home
#   layouts/partials/site-theme.html    the theme toggle's behaviour
#
# The blog's own stylesheet adds what a landing page has no use for — a list of
# posts and an article — and nothing else. A rule in it that restates something
# app.css already says is the lookalike coming back.
set -euo pipefail

here="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
check=false
[[ "${1:-}" == "--check" ]] && { check=true; shift; }
src="${1:-$here/../tacit}"

[[ -f "$src/hack/sitegen/main.go" ]] || { echo "sync-site: no tacit checkout at $src" >&2; exit 2; }

tmp=$(mktemp -d)
trap 'rm -rf "$tmp"' EXIT
( cd "$src" && go run ./hack/sitegen -o "$tmp/site" -q )

commit=$(git -C "$src" rev-parse --short HEAD 2>/dev/null || echo "unknown")
out="$tmp/out"
mkdir -p "$out/assets/css" "$out/layouts/partials" "$out/static/assets/fonts"

cp "$tmp/site/assets/app.css" "$out/assets/css/app.css"
cp "$tmp/site/assets/fonts/"* "$out/static/assets/fonts/"

# The three fragments. Extracted from the rendered page rather than from the Go
# that builds it, because the rendered page is what a reader gets: a change to
# the template, the constants or the substitution all arrive here the same way.
python3 - "$tmp/site/index.html" "$out/layouts/partials" "$commit" <<'PY'
import re, sys
page = open(sys.argv[1], encoding="utf-8").read()
outdir, commit = sys.argv[2], sys.argv[3]

def header(what):
    return ("{{/* GENERATED by hack/sync-site.sh from the landing page at %s.\n"
            "    Do not edit: %s. Run make site to refresh it. */}}\n" % (commit, what))

def write(name, body, what):
    with open(outdir + "/" + name, "w", encoding="utf-8") as f:
        f.write(header(what) + body.strip() + "\n")

# The head's prelude: everything the page loads before its stylesheet — the
# favicon, the theme it was last set to, the boot guard, and the floor of CSS
# that paints the ground before app.css arrives.
start = page.index('<link rel="icon"')
end = page.index('<link rel="stylesheet"')
write("site-head.html", page[start:end], "the landing page's head prelude")

# The masthead, by tag depth rather than by a closing tag that could be any of
# the four it contains.
i = page.index('<div class="site-masthead">')
depth, j = 0, i
for m in re.finditer(r'<(/?)div\b', page[i:]):
    depth += -1 if m.group(1) else 1
    if depth == 0:
        j = i + m.end()
        j = page.index('>', j - 1) + 1
        break
masthead = page[i:j]

# One change, and the reason for it: on the landing page the wordmark is the
# page you are already on, so it is a div and hidden from a screen reader, which
# reads the h1 instead. Here it is the way back to the product, so it becomes a
# link — and a link that is aria-hidden cannot be reached by keyboard or read
# out, so that attribute goes with the div. Everything else is the page's own
# markup, untouched.
before = masthead
masthead = masthead.replace(
    '<div class="site-wordmark" aria-hidden="true">',
    '<a class="site-wordmark" href="https://opentacit.com/">', 1)
if masthead == before:
    raise SystemExit("sync-site: the wordmark is not the div this rewrite knows how to link")
# Its closing tag, which is the first </div> after the wordmark's own contents.
k = masthead.index('<a class="site-wordmark"')
masthead = masthead[:k] + masthead[k:].replace('</div>', '</a>', 1)
for want in ['<a class="site-wordmark" href="https://opentacit.com/">', '</a>']:
    if want not in masthead:
        raise SystemExit("sync-site: the wordmark rewrite left the markup unbalanced")
if masthead.count('<div') != masthead.count('</div>'):
    raise SystemExit("sync-site: the wordmark rewrite left the masthead's divs unbalanced")
write("site-masthead.html", masthead, "the landing page's masthead, with the wordmark linked home")

# The theme toggle's behaviour, named by what it stores rather than by position.
for m in re.finditer(r'<script>.*?</script>', page, re.S):
    if "tacit-theme" in m.group(0) and "ICONS" in m.group(0):
        write("site-theme.html", m.group(0), "the landing page's theme toggle")
        break
else:
    raise SystemExit("sync-site: no theme toggle script in the rendered page")
PY

for f in assets/css/app.css layouts/partials/site-head.html \
         layouts/partials/site-masthead.html layouts/partials/site-theme.html; do
  [[ -s "$out/$f" ]] || { echo "sync-site: $f came back empty" >&2; exit 2; }
done
grep -q 'class="site-masthead"' "$out/layouts/partials/site-masthead.html" \
  || { echo "sync-site: the masthead fragment is not a masthead" >&2; exit 2; }
grep -q '/assets/fonts/' "$out/assets/css/app.css" \
  || { echo "sync-site: app.css no longer names /assets/fonts — check the font paths" >&2; exit 2; }

status=0
copy() { # copy SRC DST
  if $check; then
    diff -q "$1" "$2" >/dev/null 2>&1 || { echo "drift: ${2#$here/}" >&2; status=1; }
  else
    mkdir -p "$(dirname "$2")"; cp "$1" "$2"
  fi
}
copy "$out/assets/css/app.css" "$here/assets/css/app.css"
for p in site-head site-masthead site-theme; do
  copy "$out/layouts/partials/$p.html" "$here/layouts/partials/$p.html"
done
for f in "$out/static/assets/fonts/"*; do
  copy "$f" "$here/static/assets/fonts/$(basename "$f")"
done

if $check; then
  [[ $status -eq 0 ]] && echo "the landing page's chrome is current ($commit)" \
    || echo "run ./hack/sync-site.sh to take the current chrome ($commit)" >&2
  exit $status
fi
echo "took the landing page's chrome from $commit"
