#!/usr/bin/env bash
# Copyright 2026 The OpenTacit Authors
# SPDX-License-Identifier: Apache-2.0

# Copy the palette out of the registry's stylesheet into assets/css/tokens.css.
#
#   ./hack/sync-tokens.sh [path-to-tacit-checkout]   # write
#   ./hack/sync-tokens.sh --check [path]             # compare, exit 1 on drift
#
# The blog is a separate site on a separate host, so it cannot serve app.css —
# that file is 5,000 lines of dashboard furniture this site has no use for, and
# it is embedded in a binary rather than published. What the blog must not do is
# declare a second palette: app.css's header says every colour resolves from the
# token block, and a hand-copied hex here is how two surfaces of one product
# drift apart a shade at a time.
#
# So the tokens are copied, never retyped, and the copy names the commit it came
# from. Three blocks are taken whole: the light :root, the dark block under the
# OS preference, and the explicit data-theme="dark" block. Nothing else.
set -euo pipefail

here="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
check=false
[[ "${1:-}" == "--check" ]] && { check=true; shift; }
src="${1:-$here/../tacit}"
css="$src/internal/ui/assets/app.css"
out="$here/assets/css/tokens.css"

[[ -f "$css" ]] || { echo "sync-tokens: no app.css at $css" >&2; exit 2; }

# Each block is taken by matching braces from its opening selector, so a rule
# added or removed inside one travels with it and a line count never has to be
# right.
block() {
  awk -v start="$1" '
    index($0, start) == 1 && !done { inb = 1 }
    inb {
      print
      n = gsub(/{/, "{") - gsub(/}/, "}")
      depth += n
      if (depth == 0) { inb = 0; done = 1 }
    }
  ' "$css"
}

commit=$(git -C "$src" rev-parse --short HEAD 2>/dev/null || echo "unknown")
tmp=$(mktemp)
trap 'rm -f "$tmp"' EXIT
{
  echo "/* Copyright 2026 The OpenTacit Authors */"
  echo "/* SPDX-License-Identifier: Apache-2.0 */"
  echo
  echo "/* GENERATED by hack/sync-tokens.sh from internal/ui/assets/app.css"
  echo "   at $commit. Do not edit: edit the palette there and re-run."
  echo
  echo "   The blog takes the product's colours and nothing else. Every rule in"
  echo "   blog.css resolves from a token below, so both themes fall out of one"
  echo "   block here and a hex literal in a component is a bug. */"
  echo
  block ':root{'
  echo
  block '@media (prefers-color-scheme: dark){'
  echo
  block ':root[data-theme="dark"]{'
} > "$tmp"

# A block that came back empty means the selector moved. Fail loudly: a tokens
# file missing its dark half renders light-on-light and looks like a CSS bug.
for want in '--plane' '--accent' '--spectrum' 'data-theme="dark"'; do
  grep -q -- "$want" "$tmp" || { echo "sync-tokens: $want missing — a selector moved in app.css" >&2; exit 2; }
done

if $check; then
  if diff -q "$out" "$tmp" >/dev/null 2>&1; then
    echo "tokens.css is current ($commit)"
  else
    echo "tokens.css differs from app.css at $commit — run ./hack/sync-tokens.sh" >&2
    diff "$out" "$tmp" | head -30 >&2 || true
    exit 1
  fi
else
  cp "$tmp" "$out"
  echo "wrote $out from $commit"
fi
